"""News filtering-related constants."""

CATEGORIES = {
    "earnings": [
        "earnings",
        "quarterly",
        "revenue",
        "profit",
        "results",
        "guidance",
        "eps",
        "beat",
        "miss",
        "forecast",
        "outlook",
        "fiscal",
    ],
    "ai": [
        "artificial intelligence",
        "ai",
        "machine learning",
        "data center",
        "nvidia",
        "hyperscale",
        "cloud computing",
        "generative",
        "llm",
        "semiconductor",
        "chip",
    ],
    "capex": [
        "capital expenditure",
        "capital expenditures",
        "capex",
        "capital spending",
        "capital investment",
        "capital investments",
        "capacity expansion",
        "manufacturing expansion",
        "factory expansion",
        "facility expansion",
        "plant expansion",
        "new facility",
        "infrastructure investment",
        "property plant equipment",
    ],
    "strategy": [
        "acquisition",
        "merger",
        "partnership",
        "restructuring",
        "strategy",
        "deal",
        "agreement",
        "acquire",
        "divest",
    ],
    "operations": [
        "manufacturing",
        "supply chain",
        "production",
        "capacity",
        "logistics",
        "assembly",
        "plant",
    ],
    "cooling": [
        "liquid cooling",
        "immersion cooling",
        "thermal",
        "thermal management",
        "cooling",
        "heat exchanger",
        "cold plate",
    ],
}

AI_TERMS = [
    "ai",
    "artificial intelligence",
    "data center",
    "nvidia",
    "hyperscaler",
    "cloud",
    "llm",
    "semiconductor",
    "liquid cooling",
    "immersion cooling",
    "thermal management",
    "cooling",
]

CAPEX_TERMS = [
    "capital expenditure",
    "capital expenditures",
    "capex",
    "capital spending",
    "capital investment",
    "capital investments",
    "facility expansion",
    "capacity expansion",
    "manufacturing expansion",
    "infrastructure investment",
    "property plant equipment",
    "new facility",
    "factory expansion",
    "plant expansion",
]

BLOCKED_OR_PAYWALL_DOMAINS = {
    "wsj.com",
    "ft.com",
    "barrons.com",
    "bloomberg.com",
    "seekingalpha.com",
    "fool.com",
}

EXCLUDED_NOISE_TERMS = [
    # Sports / entertainment associations that never produce relevant EMS news.
    "fiba",
    "nba",
    "nfl",
    "nhl",
    "mlb",
    # Generic job-board / HR content that floods search results for EMS queries.
    "job opening",
    "job posting",
    "we are hiring",
    "apply now",
    "career opportunity",
    # "EMS" acronym ambiguity: FortiClient EMS is a Fortinet security product,
    # not Electronics Manufacturing Services.
    "forticlient",
    "fortinet ems",
    "emergency medical",
    "emergency management",
]
